name: proto_bytes
description: A Flutter library for binary protocol serialization and deserialization.
version: 0.9.2
homepage: https://github.com/featherJ/protobytes
environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  typed_data: ">=1.1.3 <2.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0